#include "noggit/errorHandling.h"
#include "util/log.h"

#include <csignal>
#include <string>
#include <vector>

#ifndef WIN32
  #include <execinfo.h>
#else
  #include <win/StackWalker.h>
  #include <errhandlingapi.h>
#endif

namespace noggit
{
  void printStacktrace()
  {
#ifndef WIN32
    std::vector<void*> frames  (32);

    std::size_t actual  (0);
    while ((actual = backtrace (frames.data(), frames.size())) == frames.size())
    {
      frames.resize (frames.size() * 2);
    }
    frames.resize (actual);
    char** strings (backtrace_symbols (frames.data(), frames.size()));

    LOG_DEBUG("Obtained %i stack frames.", frames.size());

    for (size_t i (0); i < frames.size(); ++i)
      LOG_DEBUG("- %s.", strings[i]);

    free (strings);
#else
    StackWalker sw;
    sw.ShowCallstack();
#endif
  }

  namespace
  {
    void leave (int sig)
    {
      // Reset to defaults.
      signal (SIGABRT, SIG_DFL);
      signal (SIGFPE, SIG_DFL);
      signal (SIGILL, SIG_DFL);
      signal (SIGSEGV, SIG_DFL);
      signal (SIGTERM, SIG_DFL);

      std::string description;
      std::string sign;

      switch (sig)
      {
      case SIGABRT:
        sign = "SIGABRT";
        description = "Abnormal termination, such as instigated by the abort function. (Abort.)";
        break;
      case SIGFPE:
        sign = "SIGFPE";
        description = "Erroneous arithmetic operation, such as divide by 0 or overflow. (Floating point exception.)";
      break;
      case SIGILL:
        sign = "SIGILL";
        description = "An ‘invalid object program’ has been detected. This usually means that there is an illegal instruction in the program. (Illegal instruction.)";
        break;
      case SIGINT:
        sign = "SIGINT";
        description = "Interactive attention signal; on interactive systems this is usually generated by typing some ‘break-in’ key at the terminal. (Interrupt.)";
        break;
      case SIGSEGV:
        sign = "SIGSEGV";
        description = "Invalid storage access; most frequently caused by attempting to store some value in an object pointed to by a bad pointer. (Segment violation.)";
        break;
      case SIGTERM:
        sign = "SIGTERM";
        description = "Termination request made to the program. (Terminate.)";
        break;
      default:
        sign = "SIGUNK";
        description = "Unknown Exception!";
        break;
      }

      LOG_FATAL("There was an exception of type '%s'\n  '%s'.\n  Please excuse the inconvenience. "
        "You may want to report this error including the log to the developers.", sign.c_str(), description.c_str());

      printStacktrace();

      exit (sig);
    }

#ifdef _WIN32
    LONG WINAPI windows_exception_handler(EXCEPTION_POINTERS * ExceptionInfo)
    {
      auto code = ExceptionInfo->ExceptionRecord->ExceptionCode;

      switch (code)
      {
      case EXCEPTION_ACCESS_VIOLATION: LOG_ERROR("EXCEPTION_ACCESS_VIOLATION."); break;
      case EXCEPTION_DATATYPE_MISALIGNMENT: LOG_ERROR("EXCEPTION_DATATYPE_MISALIGNMENT."); break;
      case EXCEPTION_BREAKPOINT: LOG_ERROR("EXCEPTION_BREAKPOINT."); break;
      case EXCEPTION_SINGLE_STEP: LOG_ERROR("EXCEPTION_SINGLE_STEP."); break;
      case EXCEPTION_ARRAY_BOUNDS_EXCEEDED: LOG_ERROR("EXCEPTION_ARRAY_BOUNDS_EXCEEDED."); break;
      case EXCEPTION_FLT_DENORMAL_OPERAND: LOG_ERROR("EXCEPTION_FLT_DENORMAL_OPERAND."); break;
      case EXCEPTION_FLT_DIVIDE_BY_ZERO: LOG_ERROR("EXCEPTION_FLT_DIVIDE_BY_ZERO."); break;
      case EXCEPTION_FLT_INEXACT_RESULT: LOG_ERROR("EXCEPTION_FLT_INEXACT_RESULT."); break;
      case EXCEPTION_FLT_INVALID_OPERATION: LOG_ERROR("EXCEPTION_FLT_INVALID_OPERATION."); break;
      case EXCEPTION_FLT_OVERFLOW: LOG_ERROR("EXCEPTION_FLT_OVERFLOW."); break;
      case EXCEPTION_FLT_STACK_CHECK: LOG_ERROR("EXCEPTION_FLT_STACK_CHECK."); break;
      case EXCEPTION_FLT_UNDERFLOW: LOG_ERROR("EXCEPTION_FLT_UNDERFLOW."); break;
      case EXCEPTION_INT_DIVIDE_BY_ZERO: LOG_ERROR("EXCEPTION_INT_DIVIDE_BY_ZERO."); break;
      case EXCEPTION_INT_OVERFLOW: LOG_ERROR("EXCEPTION_INT_OVERFLOW."); break;
      case EXCEPTION_PRIV_INSTRUCTION: LOG_ERROR("EXCEPTION_PRIV_INSTRUCTION."); break;
      case EXCEPTION_IN_PAGE_ERROR: LOG_ERROR("EXCEPTION_IN_PAGE_ERROR."); break;
      case EXCEPTION_ILLEGAL_INSTRUCTION: LOG_ERROR("EXCEPTION_ILLEGAL_INSTRUCTION."); break;
      case EXCEPTION_NONCONTINUABLE_EXCEPTION: LOG_ERROR("EXCEPTION_NONCONTINUABLE_EXCEPTION."); break;
      case EXCEPTION_STACK_OVERFLOW: LOG_ERROR("EXCEPTION_STACK_OVERFLOW."); break;
      case EXCEPTION_INVALID_DISPOSITION: LOG_ERROR("EXCEPTION_INVALID_DISPOSITION."); break;
      case EXCEPTION_GUARD_PAGE: LOG_ERROR("EXCEPTION_GUARD_PAGE."); break;
      case EXCEPTION_INVALID_HANDLE: LOG_ERROR("EXCEPTION_INVALID_HANDLE."); break;
#ifdef STATUS_POSSIBLE_DEADLOCK
      case EXCEPTION_POSSIBLE_DEADLOCK: LOG_ERROR("EXCEPTION_POSSIBLE_DEADLOCK."); break;
#endif
      default:
        LOG_ERROR("Exception code=%s.", code);
      }

      printStacktrace();

      return EXCEPTION_CONTINUE_SEARCH;
    }
#endif

  }

  void RegisterErrorHandlers()
  {
#ifdef _WIN32
    SetUnhandledExceptionFilter(windows_exception_handler);
#endif

    signal (SIGABRT, leave);
    signal (SIGFPE, leave);
    signal (SIGILL, leave);
    signal (SIGSEGV, leave);
    signal (SIGTERM, leave);
  }
}
